### ISSUE TITLE
Blue Velvet transoded my audio to 16-bit, but I need 32-bit float

### ISSUE THREAD

**Issue by unfa** [szaszak/blender_velvets#11]
Hey!

I've decided to finally give Blue Velvet a go. I capture audio for my videos in 32-bit float and that fact sometimes saves my butt.

I've noticed that Blue Velvet transcoded all my audio to 16-bit WAV.
This is insufficient for me to work with. I guess I could replace the audio files with manually demuxed WAV-s but it's going to be tedious.

Is there a way to tell Blue Velvet that I need 32-bit float audio? Or to make it not transcode the audio if it's already in  PCM, that Ardour will happily read?

**Comment by szaszak** [comment]
Hi, great that you're giving the velvets a shot. You're correct, ffmpeg downgrades all audio to 16-bit by default if we don't explicitly inform an audio codec. I've updated the code and Blue Velvet should be able to export 24-bit and 32-bit float audio now. Please update your version to the 20170827 (just remove your current Blue Velvet addon, download the addons again and reinstall) and tell me if it's working.
