### ISSUE TITLE
modified_space_sequencer does not work with blender 2.79(?)

### ISSUE THREAD

**Issue by freder** [szaszak/blender_velvets#12]
<img width="1680" alt="screen shot 2017-10-11 at 13 13 58" src="https://user-images.githubusercontent.com/724844/31437715-7f7d7966-ae86-11e7-8b2c-068d03e5f62b.png">

**Comment by szaszak** [comment]
Hi, freder, the Velvets haven't been updated for Blender 2.79 yet, so it's possible the spaec_sequencer is not working. I'll try to update them this weekend, ok?
