### ISSUE TITLE
Version for blender 2.8

### ISSUE THREAD

**Issue by G3N-es** [szaszak/blender_velvets#20]
I have adapted your plugin for 2.8. I only test it on linux.

https://drive.google.com/file/d/1D9sCyrNFbum5bxQLcgumd17RkkuxV0MT/view?usp=sharing

I commented on these two lines, because they created conflict:

        #ffCommand = preferences.addons['blue_velvet'].preferences.ffCommand
        #runFFMPEG(ffCommand, sources, audioRate, sampleFormat, audiosFolder)

Despite this, the plugin seems to do its job correctly.

I also commented on this variable, because I consider it easier to save the .adour directly where the audio sources are.

        audiosFolder = #audiosFolderPath + os.sep + "Audios_for_" + ardourBasename

Thank you for creating blueVelvet, and I hope what I send you simplify creating an official version of it for 2.8

**Comment by szaszak** [comment]
That's great @G3N-es ! Sorry for not answering before. I'm waiting for an official 2.8 version to update them, but it's so nice to see people using and adapting it - I'll surely take a look at it when the time comes.

best,

**Comment by szaszak** [comment]
Hi there @G3N-es - Blue Velvet is ready for Blender 2.80. Could you please test it if it's ok?

I took notice of your comment on using the same folder to store the audio files and it sounds like a nice idea. I will implement it as an option as soon as I have the time.

best,

**Comment by G3N-es** [comment]
Thanks!!!

**Comment by szaszak** [comment]
> I also commented on this variable, because I consider it easier to save the .adour directly where the audio sources are.

Ok, I implemented the option to choose between storing the Ardour XML inside or outside the audios folder (it's on the left panel once you go to File > Export > Ardour).

There is also now a counter showing progress when the files are being processed. This was implemented for Velvet Revolver but has similar use here.
