### ISSUE TITLE
Velvet Revolver not generating proxy

### ISSUE THREAD

**Issue by Lemente** [szaszak/blender_velvets#21]
I am trying to use the Velvets addons. I installed them apparently successfully on Blender 2.79b on Windows 10.

I tried creating the proxy by following the tutorial on your website, but when I press "Export to Revolver", nothing happens, even in the logs.

Is it a known issue? Is it a problem with Blender 2.79b?
Are the Velvet addons still supported?

Thanks !

**Comment by szaszak** [comment]
Yes, it should be working. Please double check and confirm if:

(a) once in File > External Data > Velvet Revolver you have checked one of the options in the "Export to Revolver" menu, on your lower left side of the screen - with no options checked, the addon will just return to Blender's interface; 
(b) in Blender User Preferences > Add-ons > Velvet Revolver > Preferences the path to FFMPEG is pointing either to your installed version of FFMPEG or to the downloaded FFMPEG folder where the binary/executable is. If it is, please also check via a terminal that FFMPEG is actually working from that location.

Let me know what you find out.

The Velvets are still supported but they haven't been updated to Blender 2.8 yet, even with the Release Version out there.
