### ISSUE TITLE
Error in Velvet Revolver

### ISSUE THREAD

**Issue by tin2tin** [szaszak/blender_velvets#23]
Thank you for for adding the counter, unfortunately I'm getting an error, though the path to ffmpeg is set up correctly(I'm on Windows 10):
![image](https://user-images.githubusercontent.com/1322593/66365558-b18d5180-e98d-11e9-90c0-d3d4255bef69.png)

**Comment by szaszak** [comment]
Please remove Velvet Revolver from Blender, close Blender, rename the script to velvet_revolver.py and reinstall. It should work.

**Comment by tin2tin** [comment]
Thanks, renaming the file did the trick.
