### ISSUE TITLE
Shift + Alt + S Not working in Space Sequencer

### ISSUE THREAD

**Issue by xaccrocheur** [szaszak/blender_velvets#7]
Just so you know (not really a Velvet issue I guess) Shift + Alt + S (Sets Timeline start to current frame) does nothing under Unity (Ubuntu 14.04) all the other (fantastic) KB shortcuts work. The Velvets simply rule.

**Comment by szaszak** [comment]
Hi, xaccrocheur, thanks for pointing this out. I use Debian, so I was unaware of it. Check if Shift+Alt+S is a system shortcut in Unity, perhaps that can do the trick. And thanks for the thumbs up! =)

**Comment by xaccrocheur** [comment]
I'm gonna do a video (or two) about the Velvets, it really deserves it, check it out! https://goo.gl/38Z5gn
