### ISSUE TITLE
About the website

### ISSUE THREAD

**Issue by yassinphilip** [szaszak/blender_velvets#8]
Juste a head's up : Something (maybe in the METAs) is _slightly_ broken ; How to reproduce : post http://blendervelvets.org/en/velvet-goldmine on twitter of facebook, and CSS code gets pulled. Apart from that the image and URL itself are OK.

Apart from that, The velvets are so sweet it hurts <3 Check out my last vid, 24h of Blender, no lunch break : https://www.youtube.com/watch?v=a0dm1qMWvPg

**Comment by xaccrocheur** [comment]
See this tweet as an example : https://twitter.com/yassinphilip/status/792636204822958080

**Comment by szaszak** [comment]
Hy yassin, thanks for the heads up! I was planning to tackle this problem and close this issue but whenever I tried to fiddle with wordpress Open Graph code and correct it, I never got to. The homepage does display correctly, but not the subpages - I'm not sure if this is a problem with the Wordpress Make theme or with the polylang plugin, but it still persists, after all this time. =/  I'll close the issue as not related to the addons (but to the website).
